---
title: "CleanVisualPassengers"
author: "Zheyan"
date: "11/12/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(leaflet)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "95%"
)

theme_set(theme_minimal() + theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.colour = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Clean data

Read data

```{r cars}
passenger_df = read_csv('data/passenger.csv')
```

First Groupby

```{r}
# look at it
passenger_df %>% 
  janitor::clean_names() %>% 
  filter(station == '59 ST', c_a == 'A002') %>% 
  arrange(division, scp, date, time)


# group by station and time (neglect infomation about unit/scp and ca)
passenger_df_cleaned = 
  passenger_df %>% 
    janitor::clean_names() %>% 
    mutate(entries = as.integer(entries),
           exits = as.integer(exits)) %>% 
    group_by(station, date, time) %>% 
    summarise(entries_sum = sum(entries),
              exits_sum = sum(exits),
              # ca_distinct = n_distinct(c_a),
              # unit_distinct = n_distinct(unit),
              # scp_distinct = n_distinct(scp))
             ) %>% 
    mutate(date = as.Date(date, "%m/%d/%Y")) %>% 
    arrange(station, date, time) %>% 
    ungroup()
    

```
Functions to give time period and passenger difference

```{r}
give_diff_period = function(df){
  df %>% 
    mutate(diff = entries_sum - lag(entries_sum),
           time_period = paste0(lag(time), '-', time)
           ) 
}

# try if Station '59 ST' work
df = 
  passenger_df_cleaned %>% 
    filter(station == '59 ST')

give_diff_period(df)

```

Nest data and map through all stations


```{r}
passenger_df_nested = 
  nest(passenger_df_cleaned, data = date:exits_sum)

passenger_df_final = 
  map_df(passenger_df_nested$data, ~give_diff_period(.x)) %>% 
  mutate(station = passenger_df_cleaned %>% pull(station)) %>% 
  relocate(station, date, time_period)
  

fwrite(passenger_df_final, 'passenger_cleaned.csv')
passenger_df_final

```





















