---
title: "EDA"
author: "Zheyan"
date: "11/9/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(leaflet)
library(tidyverse)
library(plotly)
##install.packages("leaflet.extras")
library(leaflet.extras)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "95%"
)

theme_set(theme_minimal() + theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.colour = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
Sys.setenv("plotly_username"="aabramov90")
Sys.setenv("plotly_api_key"="TcaNTrLIJVEJyrUlhXgd")
Sys.setenv('MAPBOX_TOKEN' = 'pk.eyJ1IjoiYWFicmFtb3Y5MCIsImEiOiJja2k5aHQ4ZWswZnhmMnNtcDJ0b2FlZzdjIn0.QcpV6ynhO9mlLga7CvUJwA')
```

## Where crime?

```{r}
df = read_csv('data/subwaycrime.csv') %>% 
  janitor::clean_names()

df %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircleMarkers(~longitude, ~latitude,radius= 3, weight= 0.5,
                   fillColor=~(boro_nm))


```

```{r}
crime_df = read_csv('data/subwaycrime_with_station.csv')

leaflet(crime_df) %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addMarkers(lat = ~latitude, lng = ~longitude,
             popup = paste("Time:",crime_df$cmplnt_fr_tm , "<br>", 
                "Offense Description:", crime_df$ofns_desc, "<br>",
                "Suspect Information", c(crime_df$susp_age_group,
                                         crime_df$susp_race,
                                         crime_df$susp_sex), "<br>",
                "Victim Information:", c(crime_df$vic_age_group,
                                         crime_df$vic_race,
                                         crime_df$vic_sex), 
                clusterOptions = markerClusterOptions())
  )
```

## adjusted by Keviant
## Top 10 offense classification
```{r}
crime_df = read_csv('data/subwaycrime_with_station.csv')
crime_df %>% 
  count(ofns_desc) %>% 
  mutate(ofns_desc = fct_reorder(ofns_desc, n)) %>% 
  slice_max(n,n=10) %>% 
  plot_ly(x = ~ofns_desc, y = ~n, color = ~ofns_desc, type = "bar", colors = "viridis") %>% 
  layout(yaxis = list(title = 'Number of Compliants'),
         xaxis = list(title = 'Type of Offense'))

## 部分代码来源 
## https://stackoverflow.com/questions/51955803/how-to-change-x-axis-layout-using-plotly-in-r
  
```

Top 20 station where crime happens frequently
```{r}
crime_df = read_csv('data/subwaycrime_with_station.csv')
crime_df %>% 
  count(closest_station) %>% 
  mutate(closest_station = fct_reorder(closest_station, n)) %>% 
  slice_max(n,n=20) %>% 
  plot_ly(x = ~closest_station, y = ~n, color = ~closest_station, type = "bar", colors = "viridis") %>% 
  layout(yaxis = list(title = 'Number of Compliants'),
         xaxis = list(title = 'Type of station'))


```

Overall function
```{r}

crime_df %>% 
  count(boro_nm) %>% 
  mutate(boro_nm = fct_reorder(boro_nm, n)) %>% 
  slice_max(n,n=20) %>% 
  plot_ly(x = ~boro_nm, y = ~n, color = ~boro_nm, type = "bar", colors = "viridis") %>% 
  layout(yaxis = list(title = 'Number of Compliants'),
         xaxis = list(title = 'Area'))
```



## Stack Bar Chart type 1
```{r}
crime_df %>% 
  count(boro_nm,susp_race) %>% 
  plot_ly(x = ~boro_nm, y = ~n, color = ~susp_race, type = "bar", colors = "viridis") %>% 
  layout(barmode="stack",
         yaxis = list(title = 'Number of Compliants'),
         xaxis = list(title = 'Area'))
```

## Stack Bar Chart type 2
```{r}

crime_df %>% 
  count(boro_nm,susp_race) %>% 
  plot_ly(x = ~boro_nm, y = ~n, color = ~susp_race, type = "bar", colors = "viridis") %>% 
  layout(
         yaxis = list(title = 'Number of Compliants'),
         xaxis = list(title = 'Area'))

```

```{r}
crime_df %>% 
  count(boro_nm,vic_race) %>% 
  plot_ly(x = ~boro_nm, y = ~n, color = ~vic_race, type = "bar", colors = "viridis") %>% 
  layout(
         yaxis = list(title = 'Number of Compliants'),
         xaxis = list(title = 'Area'))


```
## Heat Map
```{r}
crime_df %>% 
  group_by(closest_station) %>% 
  summarise(Trend=n(),
            longitude=mean(longitude),
            latitude=mean(latitude)) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addHeatmap(lng=~longitude,lat=~latitude,
             intensity=~Trend,max=100,radius=5,blur=10)

```

```{r}
crime_df %>% 
  plot_mapbox(
    lon = ~longitude, 
    lat = ~latitude, 
    color = ~boro_nm,
    mode = 'markers',
    hoverinfo = 'skip')  %>% 
  layout(
    mapbox = 
      list(
        style = 'streets',
        zoom = 9.5,
        center = list(lat = 40.7, lon = -74.0)),
      title = "Density Heatmap of Compliants in Subway")%>% 
  config(mapboxAccessToken = Sys.getenv("MAPBOX_TOKEN"))

```