---
title: "NYC subway crime"
output: 
  html_document:
    includes:
       in_header: ga_script.html
---

<link rel="stylesheet" href="academicons.css"/>
<link rel="stylesheet" href="styles.css" type="text/css">


#### Zheyan Liu, Chaoqi Wu, Baode Gao, Youyuan Kong, Zexu Yuan
#### Columbia University, Mailman School of Public Health

<br>
<center>

Word Cloud Here

</center>
<br>

## Introduction (Yuan, Kong)

New York subway, one of the main public transportation for New Yorkers, provides super convenience for local citizens, at the same time, brings potential danger to passengers, where criminals are attracted to busier subway stations for certain kinds of crime like pick pocketing. 

On November 21, around 12:00 AM, at 34th Street-Penn Station in Manhattan, Alkeem Loney, a 32-year-old male, was stabbed in the neck during an unprovoked attack and was pronounced dead later as NYPD stated. The deadly incident is the latest in a pate of violence underground that comes as the MTA tries to get commuters back on mass transit. The horrible crime event raised lots of public concern about the safety at subway stations, the safety tightly related to almost every citizen who are living, working and studying in New York City. 

As students who are living here in New York City, most of us will almost take subway to the campus in early morning and back to apartment in nights on weekdays, and hang out with friends on weekends. Safety at subway station is closely related to ourselves. We hope we are able to help citizens to find the comparatively safe and reliable routes when taking subways.

## Outcomes


## Team members



