---
title: "Proposal"
date: "11/12/2021"
output: github_document
---


# 1. Group Members: 

Zexu Yuan (zy2392), Zheyan Liu (zl3119), Baode Gao (bg2715), Keviant Kong (yk2960), Chaoqi Wu (cw3370)

# 2. The tentative project title: 

Studying crime data on subway and predicting rates
 
# 3. The motivation for this project: 

A few days ago, some members of our group was threatened with a knife on the subway. This is a serious threat to our daily life, especially in New York, where the subway is very convenient. Therefore we want to investigate the distribution of subway crime in different dimensions, the flow of passengers in the subway, and the possible connections between them. 

# 4. The intended final products: 

There will be a dashboard to show interesting facts we have uncovered from our dataset;  We will model the crime factor with time, station, passenger volume, etc. It can help us and other people to anticipate the level of danger and adopt different strategies. It is also possible to provide relevant suggestions to the NYPD based on the effect of different variables on crime factors. Finally, an application will be developed to help people.

 
# 5. The anticipated data sources:

https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Current-Year-To-Date-/5uac-w243

http://web.mta.info/developers/turnstile.html
 
# 6. The planned analyses/visualization/coding challenges: 

### i.	Data Analyses:
a.	 Most dangerous train and subway stations and most dangerous time slots in NYC
b.	Most frequent crime events
c.	The relationship between type of crime rate and the number of passengers on various time points
d.	 Most vulnerable group of citizens in NYC
e.	Factors influence crime rates

### ii.   Data Visualization: 
a.	New York Map of Subway, the depth of color referring to the crime rate, and the width of the line referring to people fluent
b.	Crime type distribution by place and time

### iii.  Coding challenges:
a.	Data cleaning and merging
b.	Data Visualization
c.	Model Analysis
d.	Application developing

# 7. The planned timeline: 

We plan to finish visualization and modeling by November 20th, report by November 27th, webpage and application by December 5th.
