---
title: "crime_rate_dash_preparation"
author: "Youyuan(Keviant) Kong"
date: "2021/12/1"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(readxl)
library(rvest)
library(httr)
library(chron)
##install.packages("chron")
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "95%"
)

theme_set(theme_minimal() + theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.colour = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r read,include=FALSE}

crime_df = read_csv('subwaycrime_with_station_new.csv')


crime_df<-crime_df %>% 
 mutate(cmplnt_fr_dt=as.Date(cmplnt_fr_dt,format='%m/%d/%Y')) %>% 
 mutate(cmplnt_to_dt=as.Date(cmplnt_to_dt,format='%m/%d/%Y')) %>% 
 filter(distance<=0.0001)%>% 
 filter(cmplnt_to_dt>='2006-1-1')

passenger_df = read_csv('passenger_imputed.csv', show_col_types = FALSE)




# just use part of features
location_df = 
  read_csv('subway_info_final3.csv', show_col_types = FALSE) %>% 
  # only keep new york
  filter(administrative_area_level_1 == 'New York') %>% 
  select(station, linename, service, sublocality, postal_code, lat, long)
  

passenger_df = 
  passenger_df %>% 
  left_join(location_df, by = c('station', 'linename')) %>% 
  drop_na(sublocality) %>% 
  relocate(station, linename, service, sublocality, postal_code, lat, long)

passenger_summary<-passenger_df %>% 
  drop_na(entry_diff_imputed,exit_diff_imputed) %>%
  group_by(postal_code,date,linename, service) %>% 
  summarise(flow=sum(entry_diff_imputed,exit_diff_imputed))

crime_summary<-crime_df %>% 
  count(postal_code,cmplnt_fr_dt,law_cat_cd,linename, service) %>% 
  pivot_wider(
    names_from ="law_cat_cd" ,
    values_from = "n"
  )

crime_rate_summary<-merge(x=passenger_summary,
                          y=crime_summary,
                          by.x=c("postal_code","date","linename","service"),
                          by.y=c("postal_code","cmplnt_fr_dt",
                                 "linename","service"),
                          all.x=TRUE)
crime_rate_summary<-crime_rate_summary %>% 
  replace(is.na(.), 0)

fwrite(crime_rate_summary,"crime_rate.csv")
  


```