---
title: "GenerateSubwayPassengerData"
author: "Zheyan"
date: "11/12/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(readxl)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "95%"
)

theme_set(theme_minimal() + theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.colour = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Merge subway info data

Every station is one obervation, merge line names and company names.

```{r}
Booth_df = read_csv('Remote-Booth-Station.xls') 

Booth_df %>%
  janitor::clean_names() %>%
  group_by(station,line_name,division) %>% 
  summarise(remote_cnt = n_distinct(remote),
            booth_cnt = n_distinct(booth)) 


Booth_df_g = 
  Booth_df %>%
    janitor::clean_names() %>%
    group_by(station) %>% 
    summarise(remote_cnt = n_distinct(remote),
              booth_cnt = n_distinct(booth),
              line_name_all = paste0(line_name, collapse = ""),
              division_all =  paste0(division, collapse = ",")) %>% 
    ungroup()


# function to drop duplicates in str (linename, divisionname)
getdistinct_str = function(str, sep){
  d <- unlist(strsplit(str, split=sep))
  paste(unique(d), collapse = ',')[[1]]
}

# try demo
str1 = "662323BCBC"
getdistinct_str(str1, '')[[1]]

Booth_df_g$line_name_all = map_chr(Booth_df_g$line_name_all, ~getdistinct_str(.x, ''))
Booth_df_g$division_all = map_chr(Booth_df_g$division_all, ~getdistinct_str(.x, ','))

```

## Get subway coordinates

### First join

```{r}
coordinates_df = read_csv('DOITT_SUBWAY_STATION_01_13SEPT2010.csv')

extract_coordinate = function(str, index){
  coordinates = str_split(substr(str, 8, nchar(str) -1), ' ')[[1]]
  as.double(coordinates[index])
}

coordinates_df$long = map_dbl(coordinates_df$the_geom, ~extract_coordinate(.x, 1))
coordinates_df$lat = map_dbl(coordinates_df$the_geom, ~extract_coordinate(.x, 2))
coordinates_df = 
  coordinates_df %>% 
  mutate(station = toupper(NAME)) %>% 
  select(station, long, lat)

coordinates_df %>% fwrite('coordinates.csv')
```



Left Join coordinates and out put final

```{r}
Booth_df_g = 
  Booth_df_g %>% 
    left_join(coordinates_df, by = 'station') 

Booth_df_g %>% 
  fwrite('station_info.csv')

```



### Second join

remove th from coordinates df (65TH ST to 65 ST)

```{r}
coordinates_df2 = coordinates_df

fancy_left_join = function(df, lookup){
  nomatch = df[is.na(df$long),] %>% select(-long, -lat)
  matched = 
    df %>% 
    drop_na()
  nomatch = 
    nomatch %>% 
    left_join(lookup, by='station')
  bind_rows(nomatch, matched)
}

coordinates_df2$station = str_replace_all(coordinates_df2$station, "TH|ND|RD", "")
Booth_df_g = fancy_left_join(Booth_df_g, coordinates_df2)

# Remove ST like (1ST ST)
coordinates_df2$station = str_replace(coordinates_df2$station, "ST", "")
Booth_df_g = fancy_left_join(Booth_df_g, coordinates_df2)
Booth_df_g[is.na(Booth_df_g$long),] %>% fwrite('manual194_subway_info.csv')
```


## Third join

Try subway crime data
```{r}

subwaycrime_df = read_csv('subwaycrime.csv')

subwaycrime_df
```











