---
title: "match_crime_station_kyy"
author: "Youyuan(Keviant) Kong"
date: "2021/11/14"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(readxl)
library(rvest)
library(httr)
library(chron)
##install.packages("chron")
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "95%"
)

theme_set(theme_minimal() + theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.colour = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## 读取这两个数据，匹配坐标(need adjusted)
```{r}
croodinate_df = read_csv('data/subway_info_final3.csv') %>% 
  janitor::clean_names()
crime_df<-read_csv('data/subwaycrime.csv') %>% 
  janitor::clean_names() %>% 
  mutate(cmplnt_fr_tm=as.character(cmplnt_fr_tm))%>% 
  select(-new_georeferenced_column) 



crime_df_total<-bind_rows(crime_df,crime_df2)
```

## 将crime里其中一行的数据粘贴到croodinate，然后依次计算distance
## 找出其中的最小值，然后选定最小的那一行
## 其中有一个错误是...最小的有两个一样的值，所以有head(1)这个代码
```{r}
croodinate_compare<-function(each){
  closet_row<-
    croodinate_df %>% 
    mutate(lat_new=crime_df_total[each,]$latitude,
         long_new=crime_df_total[each,]$longitude) %>% 
    mutate(distance=(lat_new-lat)^2+(long_new-long)^2) %>% 
    slice_min(distance,n=1) %>% 
    head(1)
  closet_row
}
crime_df_total<-crime_df_total %>% 
  drop_na(latitude,longitude)

crime_df_total<-crime_df_total %>% 
  mutate(closest_station="",
         closest_line="",
         cluster="",
         postal_code="",
         distance=0)
a<-c()
for (each in 1:nrow(crime_df_total)){
  a<-a %>% 
    bind_rows(croodinate_compare(each))
 
}
 crime_df_total[,37]= a%>% pull(station)
 crime_df_total[,38]= a%>% pull(linename)
 crime_df_total[,39]= a%>% pull(cluster)
 crime_df_total[,40]= a%>% pull(postal_code)
 crime_df_total[,41]= a%>% pull(distance)
crime_df_total %>% 
  distinct(cluster)

bigger_distance<-crime_df %>% 
  filter(distance>=.0001) %>% 
  relocate(distance,station_name,closest_station,closest_line,latitude,longitude)

crime_df_new=crime_df %>% 
  mutate(cmplnt_fr_tm=crime_df_total$cmplnt_fr_tm)
```


## match the passenger data with crime data frame

```{r}
passenger<-read.csv("data/passenger_imputed.csv") 

passenger_station<-passenger %>% 
  mutate(date=as.Date(date,format='%Y-%m-%d')) %>% 
  filter(date>='2008-12-29',date<='2021-11-05') %>% 
  drop_na(entry_diff_imputed,exit_diff_imputed) %>% 
  group_by(station, linename) %>% 
  summarise(
    flow=sum(entry_diff_imputed+exit_diff_imputed)
  )

crime_df = read_csv('subwaycrime_with_station_new.csv')

crime_df<-crime_df %>% 
 mutate(cmplnt_to_dt=as.Date(cmplnt_to_dt,format='%m/%d/%Y')) %>% 
 filter(distance<=0.0001)%>% 
 filter(cmplnt_to_dt>='2006-1-1')

crime_summary<-crime_df %>% 
  count(closest_line,closest_station) %>% 
  mutate(linename=closest_line,station=closest_station) %>% 
  select(linename,station,n)

crime_rate_summary<-merge(passenger_station,crime_summary,
                          by=c("linename","station")) %>% 
  mutate(crime_rate=n/flow)
```


## Create crime rate by time, zip code

```{r}
# passenger_summary<-passenger %>% 
#   mutate(date=as.Date(date,format='%Y-%m-%d')) %>% 
#   filter(date>='2008-12-29',date<='2021-11-05') %>% 
#   drop_na(entry_diff_imputed,exit_diff_imputed) %>% 
#   group_by(station,linename,date) %>% 
#   summarise(
#     flow=sum(entry_diff_imputed+exit_diff_imputed)
#   )


# passenger_summary<-passenger_summary%>% 
#   mutate(date=as.Date(date,format='%Y-%m-%d'))
# 
# crime_summary<-crime_summary %>% 
#  mutate(cmplnt_fr_dt=as.Date(cmplnt_fr_dt,format='%m/%d/%Y')) %>% 
#  mutate(date=cmplnt_fr_dt)
# 
# 
# crime_rate_121<-merge(x=passenger_summary,
#                           y=crime_summary,
#                           by.x=c("linename","station","date"),
#                           by.y=c("linename","station","date")) 




```


check the efficiency of matching 

```{r}
###
crime_df %>% 
  select(station_name,closest_station) %>% 
  view()

crime_df_new <-
  crime_df %>% 
    mutate(closest_station=station,
           closest_linename=linename,
           closest_line=linename) ##%>% 
##  select(-x1)





# fwrite(bigger_distance,"bigger_distance.csv")
# fwrite(crime_df_total,"subwaycrime_with_station_new.csv")
# fwrite(crime_df_new,"subwaycrime_with_station_new.csv")
# fwrite(crime_rate_summary,"crime_rate_station.csv")
# fwrite(crime_rate_121,"crime_rate_dashboard.csv")



##for (each in 1:nrow(crime_df)) {
##  crime_df[each,38]=croodinate_df %>% 
##                    mutate(lat_new=crime_df[each,]$latitude,
##                    long_new=crime_df[each,]$longitude) %>% 
##                    mutate(distance=(lat_new-lat)^2+(long_new-long)^2) ##%>%
##                    slice_min(distance,n=1) %>% 
##                    head(1) %>% 
##                    pull(station)
##   }

```